// Timezone catalog — comprehensive global list with IANA IDs.
// Offsets are computed at runtime via Intl.DateTimeFormat.
const ZONE_CATALOG = [
  // ——— Pacific (UTC-11 → UTC-8) ———
  { key: "MDY", id: "Pacific/Midway", city: "Midway", region: "US Minor Outlying", code: "MDY", emoji: "🇺🇸", dst: false, group: "Pacific" },
  { key: "PPG", id: "Pacific/Pago_Pago", city: "Pago Pago", region: "American Samoa", code: "PPG", emoji: "🇦🇸", dst: false, group: "Pacific" },
  { key: "HNL", id: "Pacific/Honolulu", city: "Honolulu", region: "Hawaii, USA", code: "HNL", emoji: "🇺🇸", dst: false, group: "Pacific" },
  { key: "ANC", id: "America/Anchorage", city: "Anchorage", region: "Alaska, USA", code: "ANC", emoji: "🇺🇸", dst: true,  group: "Americas" },
  { key: "PPT", id: "Pacific/Tahiti", city: "Tahiti", region: "French Polynesia", code: "PPT", emoji: "🇵🇫", dst: false, group: "Pacific" },

  // ——— Americas (UTC-8 → UTC-3) ———
  { key: "LA", id: "America/Los_Angeles", city: "Los Angeles", region: "USA", code: "LA",  emoji: "🇺🇸", dst: true,  group: "Americas" },
  { key: "TIJ", id: "America/Tijuana", city: "Tijuana", region: "Mexico", code: "TIJ", emoji: "🇲🇽", dst: true,  group: "Americas" },
  { key: "VAN", id: "America/Vancouver", city: "Vancouver", region: "Canada", code: "VAN", emoji: "🇨🇦", dst: true,  group: "Americas" },
  { key: "SFO", id: "America/Los_Angeles", city: "San Francisco", region: "USA", code: "SFO", emoji: "🇺🇸", dst: true,  group: "Americas", alias: true },
  { key: "SEA", id: "America/Los_Angeles", city: "Seattle", region: "USA", code: "SEA", emoji: "🇺🇸", dst: true,  group: "Americas", alias: true },
  { key: "PHX", id: "America/Phoenix", city: "Phoenix", region: "Arizona, USA", code: "PHX", emoji: "🇺🇸", dst: false, group: "Americas" },
  { key: "DEN", id: "America/Denver", city: "Denver", region: "USA", code: "DEN", emoji: "🇺🇸", dst: true,  group: "Americas" },
  { key: "YEG", id: "America/Edmonton", city: "Edmonton", region: "Canada", code: "YEG", emoji: "🇨🇦", dst: true,  group: "Americas" },
  { key: "CHI", id: "America/Chicago", city: "Chicago", region: "USA", code: "CHI", emoji: "🇺🇸", dst: true,  group: "Americas" },
  { key: "MEX", id: "America/Mexico_City", city: "Mexico City", region: "Mexico", code: "MEX", emoji: "🇲🇽", dst: false, group: "Americas" },
  { key: "YWG", id: "America/Winnipeg", city: "Winnipeg", region: "Canada", code: "YWG", emoji: "🇨🇦", dst: true,  group: "Americas" },
  { id: "America/Guatemala",    city: "Guatemala City",region: "Guatemala",  code: "GUA", emoji: "🇬🇹", dst: false, group: "Americas" },
  { key: "SJO", id: "America/Costa_Rica", city: "San José", region: "Costa Rica", code: "SJO", emoji: "🇨🇷", dst: false, group: "Americas" },
  { key: "NYC", id: "America/New_York", city: "New York", region: "USA", code: "NYC", emoji: "🇺🇸", dst: true,  group: "Americas" },
  { key: "TOR", id: "America/Toronto", city: "Toronto", region: "Canada", code: "TOR", emoji: "🇨🇦", dst: true,  group: "Americas" },
  { key: "YUL", id: "America/Montreal", city: "Montréal", region: "Canada", code: "YUL", emoji: "🇨🇦", dst: true,  group: "Americas" },
  { key: "MIA", id: "America/New_York", city: "Miami", region: "USA", code: "MIA", emoji: "🇺🇸", dst: true,  group: "Americas", alias: true },
  { key: "BOS", id: "America/New_York", city: "Boston", region: "USA", code: "BOS", emoji: "🇺🇸", dst: true,  group: "Americas", alias: true },
  { key: "HAV", id: "America/Havana", city: "Havana", region: "Cuba", code: "HAV", emoji: "🇨🇺", dst: true,  group: "Americas" },
  { key: "PTY", id: "America/Panama", city: "Panama City", region: "Panama", code: "PTY", emoji: "🇵🇦", dst: false, group: "Americas" },
  { key: "BOG", id: "America/Bogota", city: "Bogotá", region: "Colombia", code: "BOG", emoji: "🇨🇴", dst: false, group: "Americas" },
  { key: "LIM", id: "America/Lima", city: "Lima", region: "Peru", code: "LIM", emoji: "🇵🇪", dst: false, group: "Americas" },
  { key: "CCS", id: "America/Caracas", city: "Caracas", region: "Venezuela", code: "CCS", emoji: "🇻🇪", dst: false, group: "Americas" },
  { key: "LPB", id: "America/La_Paz", city: "La Paz", region: "Bolivia", code: "LPB", emoji: "🇧🇴", dst: false, group: "Americas" },
  { key: "SCL", id: "America/Santiago", city: "Santiago", region: "Chile", code: "SCL", emoji: "🇨🇱", dst: true,  group: "Americas" },
  { key: "YHZ", id: "America/Halifax", city: "Halifax", region: "Canada", code: "YHZ", emoji: "🇨🇦", dst: true,  group: "Americas" },
  { key: "SAO", id: "America/Sao_Paulo", city: "São Paulo", region: "Brazil", code: "SAO", emoji: "🇧🇷", dst: false, group: "Americas" },
  { key: "RIO", id: "America/Sao_Paulo", city: "Rio de Janeiro", region: "Brazil", code: "RIO", emoji: "🇧🇷", dst: false, group: "Americas", alias: true },
  { key: "BA", id: "America/Argentina/Buenos_Aires", city: "Buenos Aires", region: "Argentina", code: "BA",  emoji: "🇦🇷", dst: false, group: "Americas" },
  { key: "MVD", id: "America/Montevideo", city: "Montevideo", region: "Uruguay", code: "MVD", emoji: "🇺🇾", dst: false, group: "Americas" },
  { key: "YYT", id: "America/St_Johns", city: "St. John's", region: "Canada", code: "YYT", emoji: "🇨🇦", dst: true,  group: "Americas" },

  // ——— Atlantic ———
  { key: "PDL", id: "Atlantic/Azores", city: "Azores", region: "Portugal", code: "PDL", emoji: "🇵🇹", dst: true,  group: "Atlantic" },
  { key: "RAI", id: "Atlantic/Cape_Verde", city: "Praia", region: "Cape Verde", code: "RAI", emoji: "🇨🇻", dst: false, group: "Atlantic" },
  { key: "REY", id: "Atlantic/Reykjavik", city: "Reykjavík", region: "Iceland", code: "REY", emoji: "🇮🇸", dst: false, group: "Atlantic" },
  { key: "LPA", id: "Atlantic/Canary", city: "Las Palmas", region: "Canary Is.", code: "LPA", emoji: "🇪🇸", dst: true,  group: "Atlantic" },

  // ——— Europe & Africa (UTC+0 → UTC+3) ———
  { key: "LON", id: "Europe/London", city: "London", region: "UK", code: "LON", emoji: "🇬🇧", dst: true,  group: "Europe" },
  { key: "DUB", id: "Europe/Dublin", city: "Dublin", region: "Ireland", code: "DUB", emoji: "🇮🇪", dst: true,  group: "Europe" },
  { key: "LIS", id: "Europe/Lisbon", city: "Lisbon", region: "Portugal", code: "LIS", emoji: "🇵🇹", dst: true,  group: "Europe" },
  { key: "CMN", id: "Africa/Casablanca", city: "Casablanca", region: "Morocco", code: "CMN", emoji: "🇲🇦", dst: true,  group: "Africa" },
  { key: "LOS", id: "Africa/Lagos", city: "Lagos", region: "Nigeria", code: "LOS", emoji: "🇳🇬", dst: false, group: "Africa" },
  { key: "ACC", id: "Africa/Accra", city: "Accra", region: "Ghana", code: "ACC", emoji: "🇬🇭", dst: false, group: "Africa" },
  { key: "ALG", id: "Africa/Algiers", city: "Algiers", region: "Algeria", code: "ALG", emoji: "🇩🇿", dst: false, group: "Africa" },
  { key: "TUN", id: "Africa/Tunis", city: "Tunis", region: "Tunisia", code: "TUN", emoji: "🇹🇳", dst: false, group: "Africa" },
  { key: "PAR", id: "Europe/Paris", city: "Paris", region: "France", code: "PAR", emoji: "🇫🇷", dst: true,  group: "Europe" },
  { key: "BER", id: "Europe/Berlin", city: "Berlin", region: "Germany", code: "BER", emoji: "🇩🇪", dst: true,  group: "Europe" },
  { id: "Europe/Amsterdam",     city: "Amsterdam",     region: "Netherlands",code: "AMS", emoji: "🇳🇱", dst: true,  group: "Europe" },
  { key: "BRU", id: "Europe/Brussels", city: "Brussels", region: "Belgium", code: "BRU", emoji: "🇧🇪", dst: true,  group: "Europe" },
  { key: "MAD", id: "Europe/Madrid", city: "Madrid", region: "Spain", code: "MAD", emoji: "🇪🇸", dst: true,  group: "Europe" },
  { key: "BCN", id: "Europe/Madrid", city: "Barcelona", region: "Spain", code: "BCN", emoji: "🇪🇸", dst: true,  group: "Europe", alias: true },
  { key: "ROM", id: "Europe/Rome", city: "Rome", region: "Italy", code: "ROM", emoji: "🇮🇹", dst: true,  group: "Europe" },
  { key: "MXP", id: "Europe/Rome", city: "Milan", region: "Italy", code: "MXP", emoji: "🇮🇹", dst: true,  group: "Europe", alias: true },
  { id: "Europe/Zurich",        city: "Zurich",        region: "Switzerland",code: "ZRH", emoji: "🇨🇭", dst: true,  group: "Europe" },
  { key: "VIE", id: "Europe/Vienna", city: "Vienna", region: "Austria", code: "VIE", emoji: "🇦🇹", dst: true,  group: "Europe" },
  { key: "PRG", id: "Europe/Prague", city: "Prague", region: "Czechia", code: "PRG", emoji: "🇨🇿", dst: true,  group: "Europe" },
  { key: "WAW", id: "Europe/Warsaw", city: "Warsaw", region: "Poland", code: "WAW", emoji: "🇵🇱", dst: true,  group: "Europe" },
  { key: "BUD", id: "Europe/Budapest", city: "Budapest", region: "Hungary", code: "BUD", emoji: "🇭🇺", dst: true,  group: "Europe" },
  { key: "CPH", id: "Europe/Copenhagen", city: "Copenhagen", region: "Denmark", code: "CPH", emoji: "🇩🇰", dst: true,  group: "Europe" },
  { key: "STO", id: "Europe/Stockholm", city: "Stockholm", region: "Sweden", code: "STO", emoji: "🇸🇪", dst: true,  group: "Europe" },
  { key: "OSL", id: "Europe/Oslo", city: "Oslo", region: "Norway", code: "OSL", emoji: "🇳🇴", dst: true,  group: "Europe" },
  { key: "HEL", id: "Europe/Helsinki", city: "Helsinki", region: "Finland", code: "HEL", emoji: "🇫🇮", dst: true,  group: "Europe" },
  { key: "ATH", id: "Europe/Athens", city: "Athens", region: "Greece", code: "ATH", emoji: "🇬🇷", dst: true,  group: "Europe" },
  { key: "OTP", id: "Europe/Bucharest", city: "Bucharest", region: "Romania", code: "OTP", emoji: "🇷🇴", dst: true,  group: "Europe" },
  { key: "SOF", id: "Europe/Sofia", city: "Sofia", region: "Bulgaria", code: "SOF", emoji: "🇧🇬", dst: true,  group: "Europe" },
  { key: "KBP", id: "Europe/Kyiv", city: "Kyiv", region: "Ukraine", code: "KBP", emoji: "🇺🇦", dst: true,  group: "Europe" },
  { key: "IST", id: "Europe/Istanbul", city: "Istanbul", region: "Türkiye", code: "IST", emoji: "🇹🇷", dst: false, group: "Europe" },
  { key: "MOW", id: "Europe/Moscow", city: "Moscow", region: "Russia", code: "MOW", emoji: "🇷🇺", dst: false, group: "Europe" },
  { id: "Europe/Moscow",        city: "St. Petersburg",region: "Russia",     code: "LED", emoji: "🇷🇺", dst: false, group: "Europe", alias: true },
  { key: "CAI", id: "Africa/Cairo", city: "Cairo", region: "Egypt", code: "CAI", emoji: "🇪🇬", dst: false, group: "Africa" },
  { key: "JNB", id: "Africa/Johannesburg", city: "Johannesburg", region: "South Africa", code: "JNB", emoji: "🇿🇦", dst: false, group: "Africa" },
  { key: "CPT", id: "Africa/Johannesburg", city: "Cape Town", region: "South Africa", code: "CPT", emoji: "🇿🇦", dst: false, group: "Africa", alias: true },
  { key: "NBO", id: "Africa/Nairobi", city: "Nairobi", region: "Kenya", code: "NBO", emoji: "🇰🇪", dst: false, group: "Africa" },
  { key: "ADD", id: "Africa/Addis_Ababa", city: "Addis Ababa", region: "Ethiopia", code: "ADD", emoji: "🇪🇹", dst: false, group: "Africa" },
  { key: "DAR", id: "Africa/Dar_es_Salaam", city: "Dar es Salaam", region: "Tanzania", code: "DAR", emoji: "🇹🇿", dst: false, group: "Africa" },
  { key: "EBB", id: "Africa/Kampala", city: "Kampala", region: "Uganda", code: "EBB", emoji: "🇺🇬", dst: false, group: "Africa" },
  { key: "KGL", id: "Africa/Kigali", city: "Kigali", region: "Rwanda", code: "KGL", emoji: "🇷🇼", dst: false, group: "Africa" },
  { key: "KRT", id: "Africa/Khartoum", city: "Khartoum", region: "Sudan", code: "KRT", emoji: "🇸🇩", dst: false, group: "Africa" },

  // ——— Middle East (UTC+3 → UTC+4:30) ———
  { key: "TLV", id: "Asia/Jerusalem", city: "Tel Aviv", region: "Israel", code: "TLV", emoji: "🇮🇱", dst: true,  group: "Middle East" },
  { key: "AMM", id: "Asia/Amman", city: "Amman", region: "Jordan", code: "AMM", emoji: "🇯🇴", dst: true,  group: "Middle East" },
  { key: "BEY", id: "Asia/Beirut", city: "Beirut", region: "Lebanon", code: "BEY", emoji: "🇱🇧", dst: true,  group: "Middle East" },
  { key: "DAM", id: "Asia/Damascus", city: "Damascus", region: "Syria", code: "DAM", emoji: "🇸🇾", dst: true,  group: "Middle East" },
  { key: "BGW", id: "Asia/Baghdad", city: "Baghdad", region: "Iraq", code: "BGW", emoji: "🇮🇶", dst: false, group: "Middle East" },
  { key: "RUH", id: "Asia/Riyadh", city: "Riyadh", region: "Saudi Arabia", code: "RUH", emoji: "🇸🇦", dst: false, group: "Middle East" },
  { key: "DOH", id: "Asia/Qatar", city: "Doha", region: "Qatar", code: "DOH", emoji: "🇶🇦", dst: false, group: "Middle East" },
  { key: "KWI", id: "Asia/Kuwait", city: "Kuwait City", region: "Kuwait", code: "KWI", emoji: "🇰🇼", dst: false, group: "Middle East" },
  { key: "BAH", id: "Asia/Bahrain", city: "Manama", region: "Bahrain", code: "BAH", emoji: "🇧🇭", dst: false, group: "Middle East" },
  { key: "DXB", id: "Asia/Dubai", city: "Dubai", region: "UAE", code: "DXB", emoji: "🇦🇪", dst: false, group: "Middle East" },
  { key: "MCT", id: "Asia/Muscat", city: "Muscat", region: "Oman", code: "MCT", emoji: "🇴🇲", dst: false, group: "Middle East" },
  { key: "THR", id: "Asia/Tehran", city: "Tehran", region: "Iran", code: "THR", emoji: "🇮🇷", dst: false, group: "Middle East" },
  { id: "Asia/Kabul",           city: "Kabul",         region: "Afghanistan",code: "KBL", emoji: "🇦🇫", dst: false, group: "Middle East" },

  // ——— Central / South Asia (UTC+5 → UTC+6:30) ———
  { key: "KHI", id: "Asia/Karachi", city: "Karachi", region: "Pakistan", code: "KHI", emoji: "🇵🇰", dst: false, group: "Asia" },
  { key: "ISB", id: "Asia/Karachi", city: "Islamabad", region: "Pakistan", code: "ISB", emoji: "🇵🇰", dst: false, group: "Asia", alias: true },
  { key: "TAS", id: "Asia/Tashkent", city: "Tashkent", region: "Uzbekistan", code: "TAS", emoji: "🇺🇿", dst: false, group: "Asia" },
  { key: "ALA", id: "Asia/Almaty", city: "Almaty", region: "Kazakhstan", code: "ALA", emoji: "🇰🇿", dst: false, group: "Asia" },
  { key: "BOM", id: "Asia/Kolkata", city: "Mumbai", region: "India", code: "BOM", emoji: "🇮🇳", dst: false, group: "Asia" },
  { key: "DEL", id: "Asia/Kolkata", city: "New Delhi", region: "India", code: "DEL", emoji: "🇮🇳", dst: false, group: "Asia", alias: true },
  { key: "CCU", id: "Asia/Kolkata", city: "Kolkata", region: "India", code: "CCU", emoji: "🇮🇳", dst: false, group: "Asia", alias: true },
  { key: "CMB", id: "Asia/Colombo", city: "Colombo", region: "Sri Lanka", code: "CMB", emoji: "🇱🇰", dst: false, group: "Asia" },
  { key: "KTM", id: "Asia/Kathmandu", city: "Kathmandu", region: "Nepal", code: "KTM", emoji: "🇳🇵", dst: false, group: "Asia" },
  { key: "DAC", id: "Asia/Dhaka", city: "Dhaka", region: "Bangladesh", code: "DAC", emoji: "🇧🇩", dst: false, group: "Asia" },
  { key: "PBH", id: "Asia/Thimphu", city: "Thimphu", region: "Bhutan", code: "PBH", emoji: "🇧🇹", dst: false, group: "Asia" },
  { key: "RGN", id: "Asia/Yangon", city: "Yangon", region: "Myanmar", code: "RGN", emoji: "🇲🇲", dst: false, group: "Asia" },

  // ——— Southeast Asia (UTC+7 → UTC+8) ———
  { key: "BKK", id: "Asia/Bangkok", city: "Bangkok", region: "Thailand", code: "BKK", emoji: "🇹🇭", dst: false, group: "Asia" },
  { key: "SGN", id: "Asia/Ho_Chi_Minh", city: "Ho Chi Minh City", region: "Vietnam", code: "SGN", emoji: "🇻🇳", dst: false, group: "Asia" },
  { key: "HAN", id: "Asia/Ho_Chi_Minh", city: "Hanoi", region: "Vietnam", code: "HAN", emoji: "🇻🇳", dst: false, group: "Asia", alias: true },
  { key: "PNH", id: "Asia/Phnom_Penh", city: "Phnom Penh", region: "Cambodia", code: "PNH", emoji: "🇰🇭", dst: false, group: "Asia" },
  { key: "VTE", id: "Asia/Vientiane", city: "Vientiane", region: "Laos", code: "VTE", emoji: "🇱🇦", dst: false, group: "Asia" },
  { key: "JKT", id: "Asia/Jakarta", city: "Jakarta", region: "Indonesia", code: "JKT", emoji: "🇮🇩", dst: false, group: "Asia" },
  { key: "DPS", id: "Asia/Makassar", city: "Bali", region: "Indonesia", code: "DPS", emoji: "🇮🇩", dst: false, group: "Asia" },
  { key: "SIN", id: "Asia/Singapore", city: "Singapore", region: "Singapore", code: "SIN", emoji: "🇸🇬", dst: false, group: "Asia" },
  { key: "KUL", id: "Asia/Kuala_Lumpur", city: "Kuala Lumpur", region: "Malaysia", code: "KUL", emoji: "🇲🇾", dst: false, group: "Asia" },
  { id: "Asia/Manila",          city: "Manila",        region: "Philippines",code: "MNL", emoji: "🇵🇭", dst: false, group: "Asia" },
  { key: "HKG", id: "Asia/Hong_Kong", city: "Hong Kong", region: "Hong Kong", code: "HKG", emoji: "🇭🇰", dst: false, group: "Asia" },
  { key: "MFM", id: "Asia/Macau", city: "Macau", region: "Macau", code: "MFM", emoji: "🇲🇴", dst: false, group: "Asia" },
  { key: "SHA", id: "Asia/Shanghai", city: "Shanghai", region: "China", code: "SHA", emoji: "🇨🇳", dst: false, group: "Asia" },
  { key: "BJS", id: "Asia/Shanghai", city: "Beijing", region: "China", code: "BJS", emoji: "🇨🇳", dst: false, group: "Asia", alias: true },
  { key: "CKG", id: "Asia/Shanghai", city: "Chongqing", region: "China", code: "CKG", emoji: "🇨🇳", dst: false, group: "Asia", alias: true },
  { key: "URC", id: "Asia/Urumqi", city: "Ürümqi", region: "China", code: "URC", emoji: "🇨🇳", dst: false, group: "Asia" },
  { key: "TPE", id: "Asia/Taipei", city: "Taipei", region: "Taiwan", code: "TPE", emoji: "🇹🇼", dst: false, group: "Asia" },
  { key: "PER", id: "Australia/Perth", city: "Perth", region: "Australia", code: "PER", emoji: "🇦🇺", dst: false, group: "Pacific" },
  { key: "ULN", id: "Asia/Ulaanbaatar", city: "Ulaanbaatar", region: "Mongolia", code: "ULN", emoji: "🇲🇳", dst: false, group: "Asia" },

  // ——— East Asia & Pacific (UTC+9 → UTC+13) ———
  { key: "TYO", id: "Asia/Tokyo", city: "Tokyo", region: "Japan", code: "TYO", emoji: "🇯🇵", dst: false, group: "Asia" },
  { key: "OSA", id: "Asia/Tokyo", city: "Osaka", region: "Japan", code: "OSA", emoji: "🇯🇵", dst: false, group: "Asia", alias: true },
  { id: "Asia/Seoul",           city: "Seoul",         region: "South Korea",code: "ICN", emoji: "🇰🇷", dst: false, group: "Asia" },
  { id: "Asia/Pyongyang",       city: "Pyongyang",     region: "North Korea",code: "FNJ", emoji: "🇰🇵", dst: false, group: "Asia" },
  { key: "DRW", id: "Australia/Darwin", city: "Darwin", region: "Australia", code: "DRW", emoji: "🇦🇺", dst: false, group: "Pacific" },
  { key: "ADL", id: "Australia/Adelaide", city: "Adelaide", region: "Australia", code: "ADL", emoji: "🇦🇺", dst: true,  group: "Pacific" },
  { key: "BNE", id: "Australia/Brisbane", city: "Brisbane", region: "Australia", code: "BNE", emoji: "🇦🇺", dst: false, group: "Pacific" },
  { key: "SYD", id: "Australia/Sydney", city: "Sydney", region: "Australia", code: "SYD", emoji: "🇦🇺", dst: true,  group: "Pacific" },
  { key: "MEL", id: "Australia/Melbourne", city: "Melbourne", region: "Australia", code: "MEL", emoji: "🇦🇺", dst: true,  group: "Pacific" },
  { key: "HBA", id: "Australia/Hobart", city: "Hobart", region: "Australia", code: "HBA", emoji: "🇦🇺", dst: true,  group: "Pacific" },
  { key: "POM", id: "Pacific/Port_Moresby", city: "Port Moresby", region: "Papua New Guinea", code: "POM", emoji: "🇵🇬", dst: false, group: "Pacific" },
  { key: "GUM", id: "Pacific/Guam", city: "Guam", region: "Guam", code: "GUM", emoji: "🇬🇺", dst: false, group: "Pacific" },
  { key: "NOU", id: "Pacific/Noumea", city: "Nouméa", region: "New Caledonia", code: "NOU", emoji: "🇳🇨", dst: false, group: "Pacific" },
  { key: "AKL", id: "Pacific/Auckland", city: "Auckland", region: "New Zealand", code: "AKL", emoji: "🇳🇿", dst: true,  group: "Pacific" },
  { key: "WLG", id: "Pacific/Auckland", city: "Wellington", region: "New Zealand", code: "WLG", emoji: "🇳🇿", dst: true,  group: "Pacific", alias: true },
  { key: "SUV", id: "Pacific/Fiji", city: "Suva", region: "Fiji", code: "SUV", emoji: "🇫🇯", dst: false, group: "Pacific" },
  { key: "TBU", id: "Pacific/Tongatapu", city: "Nukuʻalofa", region: "Tonga", code: "TBU", emoji: "🇹🇴", dst: false, group: "Pacific" },
  { key: "APW", id: "Pacific/Apia", city: "Apia", region: "Samoa", code: "APW", emoji: "🇼🇸", dst: false, group: "Pacific" },
  { key: "CXI", id: "Pacific/Kiritimati", city: "Kiritimati", region: "Kiribati", code: "CXI", emoji: "🇰🇮", dst: false, group: "Pacific" },

  // ——— UTC reference ———
  { key: "UTC", id: "UTC", city: "UTC", region: "Coordinated Universal Time", code: "UTC", emoji: "🌐", dst: false, group: "Reference" },
];

// Quick-pick presets (most-used zones)
const QUICK_PICKS = [
  "LA", "NYC", "LON", "BER", "JNB", "DXB", "BOM", "SIN", "SGN", "SHA", "TYO", "SYD",
];

window.ZONE_CATALOG = ZONE_CATALOG;
window.QUICK_PICKS = QUICK_PICKS;
